dist: trusty
language: python
matrix:
  include:
   - python: 3.7
     os: linux
     arch: arm64
before_script:
  - python --version
install:
  - pip install --upgrade pip setuptools
script:
  - pip install -r ./build_configs/linux/requirements.txt;
  - export TRAVIS_SHORT_SHA1=$(eval echo $TRAVIS_COMMIT | cut -c -7)
  - export BUILD_FILE_NAME=eth2deposit-cli-${TRAVIS_SHORT_SHA1}-linux-amd64;
  - mkdir ${BUILD_FILE_NAME};
  - pyinstaller --distpath ./${BUILD_FILE_NAME} ./build_configs/linux/build.spec;
  - tar -zcvf ${BUILD_FILE_NAME}.tar.gz ./${BUILD_FILE_NAME};
  - mkdir /out
  - mkdir /out/artifacts;
  - cp ${BUILD_FILE_NAME}.tar.gz /out/artifacts;
 
addons:
  artifacts:
    working_dir: out
