language: python
matrix:
  include:
   - python: 3.7
     env: TOX_POSARGS="-e py37-core"
     os: linux
     arch: arm64
before_script:
  - python --version
install:
  - pip install --upgrade pip setuptools
  - pip install tox
script:
  - python --version
  - travis_wait 30 tox $TOX_POSARGS
